# Generated by Django 5.0.6 on 2024-06-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproducts',
            old_name='expire_date',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='addproducts',
            old_name='unit_in_stock',
            new_name='unit',
        ),
    ]
