# Generated by Django 5.0.6 on 2024-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_expire_date_addproducts_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='image',
            field=models.ImageField(null=True, upload_to='product/image'),
        ),
    ]
