# Generated by Django 5.0.6 on 2024-06-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_addproducts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='cat_name',
        ),
    ]
