# Generated by Django 5.0.6 on 2024-06-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_name_category_cat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproducts',
            old_name='category',
            new_name='cat_name',
        ),
    ]
